[package]
name = "birthday-tracker-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
chrono = "0.4.38"
clap = { version = "4.5.19", features = ["derive"] }
rusqlite = "0.32.1"
termcolor = "1.4.1"
